package cli

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/domehahn/skcr/internal/lockfile"
	"github.com/spf13/cobra"
)

var (
	cliAbsPathClean = filepath.Abs
	cliRemoveClean  = os.Remove
)

func newCleanCommand() *cobra.Command {
	var target string
	var plan bool
	var write bool

	cmd := &cobra.Command{
		Use:   "clean",
		Short: "Remove files previously generated by skcr",
		RunE: func(cmd *cobra.Command, args []string) error {
			if !plan && !write {
				plan = true
			}
			absTarget, err := cliAbsPathClean(target)
			if err != nil {
				return err
			}
			lock, err := cliLoadLockfile(absTarget)
			if err != nil {
				return err
			}
			stateFiles := lockfile.ManagedFilesByPath(lock)
			if len(stateFiles) == 0 {
				fmt.Println("No skcr-managed files found in .agentic-template.lock")
				return nil
			}

			fmt.Println("Clean Plan")
			fmt.Println("Action\tPath")
			for _, path := range sortedMapKeys(stateFiles) {
				fmt.Printf("remove\t%s\n", path)
			}
			if plan {
				fmt.Println("\nDry run only. Use --write to remove skcr-managed files.")
				return nil
			}
			for _, path := range sortedMapKeys(stateFiles) {
				fullPath := filepath.Join(absTarget, path)
				if err := cliRemoveClean(fullPath); err != nil && !os.IsNotExist(err) {
					return err
				}
			}
			fmt.Printf("Removed %d skcr-managed files\n", len(stateFiles))
			return nil
		},
	}

	cmd.Flags().StringVarP(&target, "target", "t", ".", "Target repository path")
	cmd.Flags().BoolVar(&plan, "plan", false, "Preview files to remove")
	cmd.Flags().BoolVar(&write, "write", false, "Remove skcr-managed files")
	return cmd
}
