package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/spf13/cobra"
)

func newExportCommand() *cobra.Command {
	var target string
	var outFile string
	var skillFilter string
	var inTarget string
	var keepFrontmatter bool

	cmd := &cobra.Command{
		Use:   "export",
		Short: "Export all skill content as a single Markdown document",
		Long: `Reads SKILL.md from every skill in .agents/skills/ and concatenates them into
a single Markdown document. Useful for injecting skills as LLM context or
producing team documentation.

By default the YAML frontmatter is stripped; use --keep-frontmatter to retain it.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			absTarget, err := filepath.Abs(target)
			if err != nil {
				return err
			}

			cfg, err := cliLoadBakeFile(filepath.Join(absTarget, "agentic.bake.yaml"))
			if err != nil {
				return err
			}

			// Collect skills to export.
			skillSeen := map[string]struct{}{}
			var skills []string

			if skillFilter != "" {
				skills = []string{skillFilter}
			} else {
				for tn, t := range cfg.Targets {
					if inTarget != "" && tn != inTarget {
						continue
					}
					for _, s := range t.Skills {
						if _, dup := skillSeen[s]; !dup {
							skillSeen[s] = struct{}{}
							skills = append(skills, s)
						}
					}
				}
				sort.Strings(skills)
			}

			if len(skills) == 0 {
				return fmt.Errorf("no skills to export")
			}

			const agentsBase = ".agents/skills"
			var sections []string
			exported, missing := 0, 0

			for _, name := range skills {
				skillMD := filepath.Join(absTarget, agentsBase, name, "SKILL.md")
				data, err := os.ReadFile(skillMD)
				if err != nil {
					missing++
					continue
				}
				content := string(data)
				if !keepFrontmatter {
					content = stripFrontmatter(content)
				}
				sections = append(sections, strings.TrimSpace(content))
				exported++
			}

			if exported == 0 {
				return fmt.Errorf("no skill SKILL.md files found — run: skcr bake --write")
			}

			var sb strings.Builder
			sb.WriteString("# Agent Skills\n\n")
			sb.WriteString(fmt.Sprintf("> Generated by `skcr export` on %s  \n", time.Now().Format("2006-01-02")))
			sb.WriteString(fmt.Sprintf("> Source: `%s`  \n", agentsBase))
			if inTarget != "" {
				sb.WriteString(fmt.Sprintf("> Target filter: `%s`  \n", inTarget))
			}
			sb.WriteString(fmt.Sprintf("> Skills: %d\n\n", exported))

			for _, section := range sections {
				sb.WriteString("---\n\n")
				sb.WriteString(section)
				sb.WriteString("\n\n")
			}

			output := sb.String()

			if outFile != "" {
				absOut := outFile
				if !filepath.IsAbs(absOut) {
					absOut = filepath.Join(absTarget, outFile)
				}
				if err := os.WriteFile(absOut, []byte(output), 0o644); err != nil {
					return fmt.Errorf("write %s: %w", outFile, err)
				}
				fmt.Fprintf(os.Stderr, "Exported %d skill(s) to %s", exported, outFile)
				if missing > 0 {
					fmt.Fprintf(os.Stderr, " (%d not yet scaffolded, skipped)", missing)
				}
				fmt.Fprintln(os.Stderr)
			} else {
				fmt.Print(output)
				if missing > 0 {
					fmt.Fprintf(os.Stderr, "Note: %d skill(s) not yet scaffolded and skipped.\n", missing)
				}
			}
			return nil
		},
	}

	cmd.Flags().StringVarP(&target, "target", "t", ".", "Repository path")
	cmd.Flags().StringVarP(&outFile, "out", "o", "", "Write output to file instead of stdout")
	cmd.Flags().StringVar(&skillFilter, "skill", "", "Export only this skill")
	cmd.Flags().StringVar(&inTarget, "in-target", "", "Export only skills from this bake target")
	cmd.Flags().BoolVar(&keepFrontmatter, "keep-frontmatter", false, "Retain YAML frontmatter in output")
	return cmd
}

// stripFrontmatter removes the leading ---...--- YAML block from a Markdown file.
func stripFrontmatter(content string) string {
	content = strings.TrimSpace(content)
	if !strings.HasPrefix(content, "---") {
		return content
	}
	// Find the closing ---
	rest := content[3:]
	end := strings.Index(rest, "\n---")
	if end == -1 {
		return content
	}
	return strings.TrimSpace(rest[end+4:])
}
