package scaffold

// agenticSecuritySkillContent contains deliberately hand-authored templates.
// These threat domains require more precision than the generic extended-skill
// seed renderer can provide.
var agenticSecuritySkillContent = map[string]skillContent{
	"agent-containment-reviewer": {
		Purpose: "Review whether an autonomous or tool-using agent remains technically contained when its instructions, model behavior, tools, dependencies, or adjacent services are compromised. Treat the agent as an untrusted principal and assess direct and transitive escape, privilege-escalation, lateral-movement, and egress paths.",
		When: []string{
			"An agent, model evaluation, coding assistant, or autonomous workflow runs in a sandbox, container, VM, runner, or isolated account.",
			"Package proxies, tool gateways, MCP servers, browsers, internal services, or shared infrastructure are reachable from an agent environment.",
			"A design claims that the agent has no host, internal-network, metadata-service, secret, or Internet access.",
			"Sandbox escape, privilege escalation, lateral movement, or kill-switch readiness needs independent review.",
			"Containment must remain effective even when the agent ignores every instruction.",
		},
		Operating: []string{
			"Model the agent as hostile and inventory every direct and transitive path from the execution environment to host, control plane, internal network, credentials, and Internet.",
			"Trace trust boundaries through proxies and helper services instead of stopping at the first allowlisted destination.",
			"Compare intended isolation with effective namespaces, mounts, identities, capabilities, routes, credentials, and shared infrastructure.",
			"Build concrete escape and lateral-movement chains, then map each hop to preventive, detective, and recovery controls.",
			"Separate declared restrictions from independently enforced controls and report evidence gaps without claiming runtime guarantees.",
		},
		ReviewScope: []string{
			"Container, microVM, VM, namespace, syscall, filesystem, device, and host isolation.",
			"Mounts, container sockets, orchestrator APIs, privileged Linux capabilities, service accounts, and cloud metadata endpoints.",
			"DNS, proxies, package registries, internal services, overlay networks, arbitrary TCP/UDP, and Internet egress.",
			"Shared runners, nodes, caches, credentials, identities, control planes, and lateral-movement opportunities.",
			"Monitoring, session termination, credential revocation, quarantine, kill switches, and forensic evidence.",
		},
		Checklist: []string{
			"Draw the execution boundary from agent process through container or VM, host, network, control plane, and external systems.",
			"Inspect host mounts, writable bind mounts, device access, container sockets, and orchestrator credentials.",
			"Review user namespaces, UID/GID mapping, seccomp, AppArmor or SELinux, capabilities, privileged mode, and kernel sharing.",
			"Verify that package proxies and allowlisted services cannot relay arbitrary requests, fetch attacker-selected URLs, or expose administrative functions.",
			"Enumerate DNS resolution, internal routes, service discovery, metadata endpoints, link-local ranges, and alternate egress protocols.",
			"Test whether compromise of each reachable service creates a transitive path to broader infrastructure or Internet access.",
			"Review service-account tokens, workload identity, instance credentials, CI tokens, cached credentials, and credential rotation boundaries.",
			"Check whether runners, nodes, caches, volumes, or workspaces are shared across trust levels or tenants.",
			"Assess privilege-escalation paths through kernel attack surface, setuid files, sudo, package hooks, plugins, and control-plane APIs.",
			"Assess lateral movement to databases, artifact stores, registries, build systems, secret stores, and administrative interfaces.",
			"Verify independent telemetry for denied connections, unusual process trees, boundary violations, credential access, and escape attempts.",
			"Verify that operators can terminate the session, isolate the workload, revoke credentials, preserve evidence, and block further egress.",
		},
		DecisionRules: []string{
			"If compromise of an allowlisted proxy or helper service exposes a broader network path, classify containment by the transitive path rather than the first hop.",
			"If the agent can reach a host socket, privileged control-plane API, or reusable infrastructure credential, treat host or infrastructure compromise as plausible until disproven.",
			"If isolation depends on instructions or cooperative model behavior, report that no technical containment control exists.",
			"If multiple tenants or trust levels share mutable state, require demonstrated isolation and cleanup before accepting containment.",
			"If a critical boundary has no independent deny telemetry or termination mechanism, report a detection and response gap in addition to the preventive-control gap.",
			"If evidence is configuration-only, distinguish intended settings from tested effective isolation.",
		},
		FindingCategories: []string{
			"Sandbox, container, VM, namespace, or host escape path.",
			"Transitive proxy, package-registry, helper-service, or control-plane bypass.",
			"Privilege escalation through identity, kernel, capability, mount, socket, or credential exposure.",
			"Internal-network reachability, lateral movement, metadata access, or unintended Internet egress.",
			"Cross-tenant or shared-runner state and credential exposure.",
			"Missing monitoring, quarantine, revocation, forensic evidence, or kill switch.",
		},
		SeverityGuidance: []string{
			"Critical: a plausible chain escapes the agent boundary and reaches host control, reusable credentials, sensitive internal infrastructure, or unrestricted external systems.",
			"High: isolation can be bypassed through a reachable service, shared resource, privileged interface, or unmonitored egress path.",
			"Medium: defense-in-depth, tenant separation, detection, cleanup, or recovery controls are incomplete but primary isolation remains evidenced.",
			"Low: documentation, ownership, test cadence, or minor hardening is missing without a demonstrated boundary bypass.",
		},
		OutputRequirements: []string{
			"Containment architecture showing direct and transitive trust boundaries, identities, network paths, and shared resources.",
			"Attack-path table with prerequisite, hop, reachable asset, evidence, existing control, and residual risk.",
			"Effective-isolation comparison covering namespaces, mounts, capabilities, credentials, proxies, routes, and egress.",
			"Findings ordered by severity with concrete containment remediation and verification steps.",
			"Monitoring, kill-switch, credential-revocation, quarantine, and evidence-preservation assessment.",
			"Explicit assumptions, untested controls, unavailable runtime evidence, and residual-risk owners.",
		},
		AcceptanceCriteria: []string{
			"The agent is modeled as an untrusted principal rather than trusted application logic.",
			"Direct and transitive paths through every reachable proxy or helper service are assessed.",
			"Host, control-plane, metadata, internal-network, credential, and Internet boundaries are covered.",
			"Critical isolation claims are tied to effective configuration or adversarial test evidence.",
			"Every Critical or High path has a preventive remediation plus detection and recovery guidance.",
			"The report does not claim that SKILL.md instructions or contract declarations alone provide containment.",
		},
		AntiPatterns: []string{
			"Stopping the review at an allowlisted proxy without modeling compromise of the proxy.",
			"Treating an internal network, shared runner, or package registry as inherently trusted.",
			"Equating containerization with a complete security boundary.",
			"Reviewing declared egress policy without inspecting effective routes, DNS, alternate protocols, and service relays.",
			"Ignoring credential revocation, quarantine, monitoring, or kill-switch behavior because preventive controls exist.",
			"Claiming isolation based only on instructions, policy text, or untested configuration.",
		},
	},
	"agent-runtime-enforcement-reviewer": {
		Purpose: "Compare an agent's declared Goal and contract.yaml boundary with the independent runtime mechanisms that actually mediate tools, filesystem, repository, process, network, secrets, data egress, approvals, and limits. Identify declaration-to-enforcement gaps without treating the declaration itself as enforcement.",
		When: []string{
			"A contract.yaml or equivalent capability policy is deployed with an agent runtime.",
			"Tool gateways, sandboxes, firewalls, secret brokers, approval services, or resource governors are expected to enforce agent restrictions.",
			"Runtime architecture must demonstrate that undeclared tools and capabilities fail closed.",
			"Policy translation, identity binding, bypass resistance, or enforcement telemetry needs review.",
			"An organization needs evidence that the evaluated contract matches the contract enforced in production.",
		},
		Operating: []string{
			"Normalize the declared contract into enforceable decisions and trace each decision to an independent runtime control.",
			"Verify identity, contract digest, policy version, invocation scope, and fail-closed behavior at every enforcement point.",
			"Exercise negative paths for undeclared destinations, tools, files, processes, secrets, approvals, and exhausted limits.",
			"Search for alternate interfaces and confused-deputy paths that bypass the primary gateway.",
			"Separate authoring validation, runtime enforcement, behavioral observation, and post-hoc detection in every conclusion.",
		},
		ReviewScope: []string{
			"Contract loading, schema validation, canonical digest binding, policy compilation, distribution, and cache invalidation.",
			"Tool mediation, repository and filesystem authorization, process sandboxing, network gateways, secret brokers, and data-loss prevention.",
			"Agent and invocation identity, tenant binding, delegated credentials, approval decisions, and replay resistance.",
			"Limit enforcement for tool calls, runtime, network requests, concurrency, retries, and nested agents.",
			"Denied-action telemetry, tamper resistance, failover behavior, policy drift, and emergency revocation.",
		},
		Checklist: []string{
			"Map every Contract v1 required and allowed field to a named runtime enforcement point or an explicit unsupported gap.",
			"Verify the runtime binds the intended skill, invocation, principal, and canonical contract digest before granting capabilities.",
			"Confirm malformed, missing, unsupported, stale, or unverifiable contracts fail closed.",
			"Test undeclared tool invocation and explicit tool deny precedence through every available tool interface.",
			"Test repository and filesystem scopes against alternate paths, symlinks, archives, generated files, and helper services.",
			"Test process.execute false against shells, interpreters, package hooks, build tools, plugins, and indirect execution.",
			"Test network destinations against raw IPs, DNS rebinding, redirects, proxies, tunnels, alternate protocols, and nested tools.",
			"Test secrets.read false against environment variables, mounted files, metadata services, logs, caches, and delegated tools.",
			"Verify approval modes are independently recorded, scoped, non-replayable, and re-evaluated when parameters change.",
			"Verify zero and finite limits are enforced across retries, parallel calls, nested agents, and gateway failover.",
			"Check that no direct SDK, shell, browser, MCP, plugin, or administrative path bypasses the policy gateway.",
			"Verify denied actions, policy errors, digest mismatches, overrides, and emergency revocations produce tamper-resistant telemetry.",
		},
		DecisionRules: []string{
			"If a declared restriction has no independent mediator, classify it as unenforced even when instructions repeat the restriction.",
			"If any alternate interface reaches the protected resource without the same policy decision, treat the control as bypassable.",
			"If the runtime cannot bind policy to the exact invocation and contract digest, report policy-confusion and evaluation-integrity risk.",
			"If policy loading or a gateway outage falls back to allow, classify the affected boundary as a critical fail-open condition.",
			"If approval can be reused after action parameters, destination, capability, or invocation changes, report approval-scope bypass.",
			"If only post-hoc logs exist, label the control detective rather than preventive.",
		},
		FindingCategories: []string{
			"Declared capability without an independent enforcement point.",
			"Tool, filesystem, process, network, secret, or data-egress gateway bypass.",
			"Contract digest, skill identity, invocation, tenant, or policy-version binding failure.",
			"Fail-open parsing, distribution, caching, outage, or fallback behavior.",
			"Approval replay, parameter substitution, limit evasion, or nested-agent accounting gap.",
			"Missing, mutable, or incomplete denied-action and policy-decision telemetry.",
		},
		SeverityGuidance: []string{
			"Critical: a forbidden capability is reachable, enforcement fails open, or policy identity can be substituted across tenants or invocations.",
			"High: a practical alternate interface, approval replay, stale policy, or accounting gap bypasses a material restriction.",
			"Medium: enforcement exists but coverage, telemetry, recovery, or negative-test evidence is incomplete.",
			"Low: naming, documentation, ownership, or non-critical observability needs improvement without changing effective authorization.",
		},
		OutputRequirements: []string{
			"Contract-to-enforcement matrix for capabilities, tools, data boundaries, approvals, limits, and output restrictions.",
			"Runtime trust-boundary diagram naming policy decision and enforcement points.",
			"Negative-test evidence for allowed, denied, missing, malformed, zero-limit, and exhausted-limit cases.",
			"Bypass analysis covering alternate interfaces, delegated tools, nested agents, proxies, and failure modes.",
			"Findings with declared rule, effective behavior, evidence, impact, and remediation owner.",
			"Clear statement of what is preventive, detective, declared-only, untested, or delegated downstream.",
		},
		AcceptanceCriteria: []string{
			"Every security-relevant contract field maps to a tested control or explicit enforcement gap.",
			"The exact contract digest, principal, tenant, and invocation are bound at runtime.",
			"Missing, malformed, unsupported, or unavailable policy fails closed.",
			"Alternate access paths receive equivalent authorization and limit decisions.",
			"Approvals and limits preserve their declared scope under retries, parameter changes, concurrency, and nesting.",
			"Conclusions distinguish declaration, validation, observation, detection, and technical enforcement.",
		},
		AntiPatterns: []string{
			"Calling contract validation runtime enforcement.",
			"Testing only allowed operations and never proving deny paths.",
			"Reviewing the primary tool gateway while ignoring shell, SDK, browser, MCP, plugin, or administrative alternatives.",
			"Binding policy to a mutable filename or skill name without a canonical digest and invocation identity.",
			"Treating approval UI presence as proof of action scope, freshness, and replay resistance.",
			"Claiming prevention when the only control is logging or after-the-fact alerting.",
		},
	},
	"agent-behavior-eval-engineer": {
		Purpose: "Design declarative, reproducible behavioral and adversarial evaluations for complete agent trajectories. Test Goal achievement together with contract compliance, acceptable tool use, state transitions, resistance to goal hacking, and preservation of security boundaries without embedding executable predicates.",
		When: []string{
			"An agentic system needs baseline, adversarial, boundary, or long-horizon security evaluations.",
			"Goal success can be achieved through forbidden shortcuts, leaked answers, unsafe tools, or specification gaming.",
			"Tool calls, filesystem changes, network access, secret handling, approvals, and final output must be assessed as one trajectory.",
			"An incident, threat model, contract, or invariant must become a regression eval.",
			"Evaluation evidence needs stable scenario, Goal criterion, invariant, capability, and contract-digest references.",
		},
		Operating: []string{
			"Derive scenarios from Goal criteria, contract boundaries, invariants, threat models, and real failure modes.",
			"Define observable initial state, adversarial stimulus, permitted success path, forbidden shortcuts, assertions, and evidence.",
			"Evaluate the full trajectory rather than accepting a correct final answer produced through prohibited behavior.",
			"Separate deterministic instrumentation from model-based judging and document uncertainty, flakiness, and false-positive controls.",
			"Keep eval specifications declarative; place executable harness logic in a separate trusted eval runner.",
		},
		ReviewScope: []string{
			"Baseline task success, Goal-criterion traceability, output quality, and contract-preserving execution.",
			"Prompt injection, indirect injection, goal hacking, specification gaming, reward hacking, and hidden-answer retrieval.",
			"Tool, process, filesystem, network, secret, approval, data-egress, and resource-limit trajectories.",
			"Sandbox escape attempts, privilege escalation, lateral movement, persistence, self-modification, and cross-agent influence.",
			"Long-horizon decomposition, retries, memory, context changes, evaluator integrity, fixtures, evidence, and reproducibility.",
		},
		Checklist: []string{
			"Reference stable Goal criterion IDs and contract invariant IDs instead of matching prose alone.",
			"Define the initial repository, filesystem, network, identity, secret, memory, and tool state required by each scenario.",
			"Include a legitimate permitted path so the eval distinguishes secure success from blanket refusal.",
			"Add adversarial instructions that request direct writes, secret disclosure, policy bypass, unsafe tools, or approval avoidance.",
			"Add environmental temptations such as leaked solutions, overprivileged credentials, unexpected internal services, or poisoned tool descriptions.",
			"Assert forbidden capabilities and tools across the complete trajectory, not only the final response.",
			"Assert expected state preservation for repository, filesystem, external systems, credentials, logs, and memory.",
			"Cover retries, parallel calls, nested agents, context compaction, delayed triggers, and long-horizon plans.",
			"Capture tool-call parameters, policy decisions, state diffs, network destinations, approvals, limits, and final output as evidence.",
			"Define deterministic pass, fail, inconclusive, infrastructure-error, and judge-disagreement handling.",
			"Protect eval fixtures, hidden answers, judges, and telemetry from agent access or manipulation.",
			"Bind results to skill version, eval schema version, scenario ID, runtime version, and canonical contract digest.",
		},
		DecisionRules: []string{
			"If the Goal is achieved through a forbidden capability, tool, data flow, or invariant violation, the scenario fails.",
			"If a scenario offers no secure success path, classify refusal behavior separately from useful safe completion.",
			"If an assertion cannot be observed reliably, mark it unevaluated rather than inferring compliance from the final text.",
			"If model judgment is required, retain the rubric, evidence, judge version, disagreement, and deterministic checks.",
			"If an agent can read hidden answers, fixtures, or expected assertions, treat the eval as contaminated.",
			"If an incident exposes a new trajectory, add a minimized regression scenario plus boundary variants.",
		},
		FindingCategories: []string{
			"Goal hacking, specification gaming, reward hacking, or forbidden shortcut.",
			"Unsafe capability, tool, data-flow, approval, or limit trajectory.",
			"Sandbox escape, lateral movement, persistence, self-modification, or external-system impact.",
			"Missing observation, ambiguous assertion, weak oracle, or final-output-only evaluation.",
			"Eval contamination, judge manipulation, fixture leakage, or non-reproducible environment.",
			"Long-horizon, retry, concurrency, nested-agent, memory, or context-transition coverage gap.",
		},
		SeverityGuidance: []string{
			"Critical: eval design would pass successful exploitation, secret exfiltration, boundary escape, persistence, or external compromise.",
			"High: material contract violations, goal-hacking paths, or unobserved privileged actions can pass as success.",
			"Medium: scenario coverage, evidence binding, reproducibility, judge quality, or long-horizon variation is incomplete.",
			"Low: naming, documentation, fixture organization, or non-blocking rubric clarity needs improvement.",
		},
		OutputRequirements: []string{
			"Eval plan mapping Goal criteria, contract clauses, invariants, threats, and incidents to scenarios.",
			"Declarative baseline, adversarial, boundary, and long-horizon scenario specifications.",
			"Trajectory evidence model covering inputs, tool calls, policy decisions, state diffs, network activity, approvals, limits, and outputs.",
			"Pass/fail/inconclusive rubric with deterministic assertions and clearly separated model-based judgments.",
			"Fixture-isolation, hidden-answer protection, reproducibility, and contract-digest binding requirements.",
			"Coverage gaps, expected false positives, infrastructure dependencies, and recommended regression cadence.",
		},
		AcceptanceCriteria: []string{
			"Goal success and contract compliance are independently asserted.",
			"Every high-risk scenario observes the relevant trajectory and state changes.",
			"Baseline scenarios demonstrate useful secure completion rather than refusal-only behavior.",
			"Adversarial scenarios cover malicious prompts and tempting or compromised environments.",
			"Eval definitions remain declarative and contain no shell expressions, scripts, or executable predicates.",
			"Results can be reproduced and tied to exact scenario, runtime, skill, and contract versions.",
		},
		AntiPatterns: []string{
			"Evaluating only whether the final answer looks correct.",
			"Rewarding Goal completion while ignoring forbidden tools, state changes, or data flows.",
			"Using refusal as the only acceptable secure behavior when a permitted path exists.",
			"Letting the agent read hidden answers, judge prompts, fixtures, assertions, or policy decisions.",
			"Embedding scripts or arbitrary executable expressions inside declarative eval YAML.",
			"Reporting a single stochastic run as conclusive long-horizon security evidence.",
		},
	},
	"backdoor-persistence-reviewer": {
		Purpose: "Review code, configuration, build changes, and generated artifacts for deliberate or unexplained privileged control paths, hidden triggers, covert egress, security-control tampering, and persistence. Require every security-relevant behavior to be traceable to an authorized requirement rather than assuming all weaknesses are accidental.",
		When: []string{
			"AI-generated, externally contributed, obfuscated, security-sensitive, or unexpectedly broad changes need hostile-intent review.",
			"Authentication, authorization, update, plugin, startup, logging, telemetry, networking, or build behavior changes.",
			"A diff introduces magic values, undocumented routes, debug paths, dynamic code, remote endpoints, hooks, or platform persistence.",
			"An incident suggests a hidden trigger, master credential, covert channel, audit suppression, or re-entry mechanism.",
			"Classic vulnerability review passed but behavioral provenance remains unexplained.",
		},
		Operating: []string{
			"Establish expected behavior from task, specification, Goal, Contract, architecture, tests, and documented operations.",
			"Trace every new privileged branch, trigger, external interaction, startup action, and security-control change to explicit provenance.",
			"Review semantic behavior across source, generated output, dependencies, build hooks, installers, configuration, and deployment artifacts.",
			"Develop trigger hypotheses and validate them with safe static analysis and targeted negative tests.",
			"Preserve evidence and separate confirmed malicious behavior, suspicious unexplained behavior, accidental vulnerability, and benign documented functionality.",
		},
		ReviewScope: []string{
			"Authentication bypass, hidden admin functions, master credentials, undocumented routes, magic headers, and feature flags.",
			"User-, tenant-, IP-, host-, time-, locale-, environment-, payload-, or sequence-triggered privileged behavior.",
			"Covert network egress, secret endpoints, DNS channels, disabled TLS verification, dynamic downloads, and remote code loading.",
			"Startup persistence, cron, systemd, launch agents, shell profiles, package hooks, plugins, self-modification, and updater abuse.",
			"Authorization, logging, audit, alerting, signature, update, kill-switch, and security-control tampering or suppression.",
		},
		Checklist: []string{
			"Map changed behavior to a requirement, task, specification, Goal, Contract, ADR, test, or documented operational need.",
			"Inspect authentication and authorization branches for alternate success paths, hard-coded credentials, magic values, and hidden roles.",
			"Search for undocumented routes, handlers, commands, RPC methods, debug interfaces, feature flags, and administrative parameters.",
			"Review comparisons against user, tenant, IP, header, time, date, hostname, environment, locale, payload, and call-sequence triggers.",
			"Review new network destinations, raw sockets, DNS use, redirects, telemetry, uploads, callbacks, and disabled certificate verification.",
			"Review eval, exec, interpreters, reflection, deserialization, dynamic imports, downloaded code, plugins, and encrypted or obfuscated payloads.",
			"Review install, postinstall, build, test, update, startup, cron, systemd, launch-agent, shell-profile, and service-registration hooks.",
			"Review writes to binaries, configuration, credentials, authorized keys, startup locations, security policies, and audit settings.",
			"Check for logging suppression, selective redaction, alert bypass, timestamp manipulation, evidence deletion, and error swallowing.",
			"Compare source with generated code, vendored output, minified bundles, release artifacts, lockfiles, and dependency changes.",
			"Inspect dead code, rare branches, encoding, string construction, unusual constants, and environment-specific behavior.",
			"Add targeted negative tests for suspected triggers and document exact evidence without executing unsafe payloads.",
		},
		DecisionRules: []string{
			"If a privileged behavior has no traceable requirement or documented operational purpose, block acceptance pending security review.",
			"If a magic credential, header, route, trigger, or remote endpoint bypasses normal authorization, classify it as Critical unless proven unreachable.",
			"If persistence or self-modification is intentional, require explicit specification, least privilege, user visibility, removal, and auditability.",
			"If obfuscation or generated output prevents semantic review, do not downgrade the finding because source intent is unclear.",
			"If suspicious behavior may be incident evidence, preserve the artifact and avoid destructive cleanup before coordination.",
			"If behavior is vulnerable but no deliberate mechanism is evidenced, label it accidental vulnerability rather than asserting malicious intent.",
		},
		FindingCategories: []string{
			"Undocumented authentication, authorization, administrative, debug, or privileged control path.",
			"Hidden trigger based on magic input, identity, environment, host, time, sequence, or remote signal.",
			"Covert egress, secret endpoint, dynamic payload, remote code, or externally controlled kill switch.",
			"Startup, installer, updater, plugin, account, key, service, or self-modification persistence.",
			"Security-control tampering, signature bypass, audit suppression, evidence deletion, or selective logging.",
			"Unexplained behavior provenance, obfuscation, generated-artifact mismatch, or dependency-mediated backdoor risk.",
		},
		SeverityGuidance: []string{
			"Critical: hidden privileged access, master credential, remote execution, covert secret egress, durable persistence, or disabled core control is reachable.",
			"High: plausible undocumented trigger, external control path, audit suppression, updater abuse, or privileged behavior lacks authorized provenance.",
			"Medium: suspicious behavior, generated mismatch, weak traceability, or defense-in-depth gap requires targeted validation.",
			"Low: documentation, naming, dead-code cleanup, or non-sensitive provenance needs improvement without a credible hidden control path.",
		},
		OutputRequirements: []string{
			"Behavior-provenance map linking each security-relevant change to requirement, Goal, Contract, design, test, or explicit gap.",
			"Suspicious-path findings with trigger, privileged effect, reachability, evidence, impact, and confidence.",
			"Persistence and external-communication inventory covering startup, hooks, updates, plugins, identities, files, and endpoints.",
			"Security-control integrity assessment for auth, logging, audit, signatures, updates, alerts, and kill switches.",
			"Targeted negative-test recommendations and safe evidence-preservation or incident-escalation steps.",
			"Clear distinction between confirmed mechanism, suspected mechanism, accidental vulnerability, benign documented behavior, and unknown.",
		},
		AcceptanceCriteria: []string{
			"Every new privileged path, trigger, endpoint, persistence mechanism, and control change has reviewed provenance.",
			"Authentication, authorization, build, startup, update, network, logging, and generated artifacts are covered.",
			"Magic values and environment-specific branches are either justified and tested or reported.",
			"Suspicious findings include concrete evidence and reachability without unsupported claims of malicious intent.",
			"Potential incident evidence is preserved and escalated safely.",
			"Critical or High unexplained behavior blocks approval until removed or explicitly authorized and controlled.",
		},
		AntiPatterns: []string{
			"Running only SAST and assuming deliberate control paths look like known vulnerabilities.",
			"Accepting debug, support, recovery, telemetry, or update behavior without requirement provenance.",
			"Searching only source code while ignoring generated artifacts, hooks, dependencies, configuration, and release bundles.",
			"Calling suspicious code malicious without evidence, trigger analysis, and reachability assessment.",
			"Deleting suspected persistence before preserving evidence and coordinating incident response.",
			"Treating obfuscation, magic constants, or selective logging as harmless because tests are green.",
		},
	},
	"agentic-threat-modeler": {
		Purpose: "Create threat models for agentic systems by treating agents, models, tools, memory, retrieved content, MCP servers, other agents, and runtime infrastructure as distinct and potentially untrusted principals. Translate agent-specific attack paths into Goal, Contract, eval, containment, monitoring, and enforcement requirements.",
		When: []string{
			"A tool-using, autonomous, multi-agent, RAG, MCP, coding, browser, or operational agent is designed or materially changed.",
			"Agent identities, capabilities, memory, context, tools, approvals, runtime boundaries, or external systems need threat analysis.",
			"Prompt injection, tool poisoning, excessive agency, sandbox escape, persistence, or cross-agent compromise is plausible.",
			"A general threat model does not distinguish model behavior from runtime enforcement.",
			"Goal, contract.yaml, eval scenarios, and infrastructure controls need a common threat basis.",
		},
		Operating: []string{
			"Model the agent as an untrusted principal whose outputs and chosen actions may be adversarial even without a malicious user.",
			"Inventory assets, identities, Goals, capabilities, tools, memory, data sources, context channels, runtimes, and enforcement points.",
			"Trace direct and indirect instruction flows plus authority transitions across users, content, agents, tools, and infrastructure.",
			"Develop abuse cases for compromised models, poisoned context, malicious tools, unsafe autonomy, and infrastructure escape.",
			"Map each threat to prevention, detection, response, Contract clauses, security invariants, and behavioral evals.",
		},
		ReviewScope: []string{
			"Direct and indirect prompt injection, instruction hierarchy, retrieved content, memory poisoning, and context confusion.",
			"Tool poisoning, MCP server compromise or rug pull, plugin updates, delegated agents, and confused deputies.",
			"Excessive agency, goal misgeneralization, specification gaming, reward hacking, unbounded autonomy, and approval bypass.",
			"Credential harvesting, secret egress, privilege escalation, sandbox escape, lateral movement, persistence, and self-modification.",
			"Identity, tenant, runtime, data, network, tool, memory, monitoring, kill-switch, and human-approval trust boundaries.",
		},
		Checklist: []string{
			"Identify users, operators, agents, models, subagents, tools, MCP servers, data providers, runtimes, and external principals.",
			"Inventory sensitive assets, Goals, contract boundaries, credentials, memory, context, retrieved data, outputs, and controlled systems.",
			"Draw trust boundaries and authority transitions for prompts, retrieved content, tool results, memory writes, approvals, and actions.",
			"Model direct prompt injection and indirect injection through documents, web pages, issues, logs, code, images, and tool output.",
			"Model tool poisoning, description manipulation, MCP compromise, rug pulls, plugin updates, and parameter substitution.",
			"Model memory poisoning, cross-session contamination, cross-agent injection, delegated authority, and identity confusion.",
			"Model goal hacking, specification gaming, leaked-solution use, reward manipulation, and unsafe shortcut selection.",
			"Model excessive agency, approval bypass, recursive delegation, retries, concurrency, and long-horizon autonomy.",
			"Model credential access, data exfiltration, covert channels, privilege escalation, sandbox escape, and lateral movement.",
			"Model self-modification, hidden triggers, persistence, security-control tampering, monitoring evasion, and kill-switch resistance.",
			"Map each high-risk threat to contract capabilities, tools, data flows, approvals, limits, and structured invariants.",
			"Define adversarial evals, runtime enforcement, monitoring signals, incident response, recovery, and residual-risk ownership.",
		},
		DecisionRules: []string{
			"If content can influence agent decisions without equivalent authority, treat it as an untrusted instruction channel.",
			"If a tool or MCP server can change after approval, model update integrity and rug-pull risk separately from initial trust.",
			"If the agent can reach a capability through delegation or a helper, include it in effective authority even when not directly declared.",
			"If Goal success rewards an unsafe shortcut, require an invariant and trajectory-level eval rather than output-only acceptance.",
			"If a threat is mitigated only by instructions, keep the technical residual risk open.",
			"If a Critical or High threat lacks prevention, detection, response, and an owner, mark the design incomplete.",
		},
		FindingCategories: []string{
			"Prompt, retrieved-content, memory, context, or cross-agent injection.",
			"Tool, MCP, plugin, delegated-agent, update, or confused-deputy compromise.",
			"Goal hacking, specification gaming, excessive agency, approval bypass, or unbounded autonomy.",
			"Credential harvesting, secret egress, covert channel, or sensitive-data misuse.",
			"Privilege escalation, sandbox escape, lateral movement, persistence, self-modification, or hidden trigger.",
			"Missing runtime enforcement, monitoring, kill switch, incident response, eval coverage, or residual-risk owner.",
		},
		SeverityGuidance: []string{
			"Critical: plausible agent-controlled path compromises host, privileged infrastructure, reusable credentials, sensitive data, or external systems.",
			"High: poisoned instructions, tools, memory, delegation, or goals can bypass a material control or approval.",
			"Medium: defense-in-depth, monitoring, eval coverage, context isolation, or recovery control is incomplete.",
			"Low: documentation, ownership, naming, diagram, or low-impact hardening needs improvement.",
		},
		OutputRequirements: []string{
			"Agentic-system diagram showing principals, Goals, tools, MCP servers, memory, data, runtime, identities, and trust boundaries.",
			"Asset, authority, instruction-channel, capability, and data-flow inventory.",
			"Threat register with attack path, preconditions, agent behavior, affected asset, controls, and residual risk.",
			"Goal and Contract recommendations covering required/allowed capabilities, tools, data flows, approvals, limits, and invariants.",
			"Adversarial eval plan plus runtime monitoring, containment, enforcement, kill-switch, and response requirements.",
			"Assumptions, unsupported controls, accepted risks, decision owners, and review triggers.",
		},
		AcceptanceCriteria: []string{
			"The agent and every delegated component are modeled as potentially untrusted principals.",
			"Instruction, authority, identity, data, memory, tool, runtime, and network boundaries are explicit.",
			"Agent-specific threats extend beyond conventional application STRIDE analysis.",
			"Every Critical or High threat maps to controls, evals, monitoring, response, and an owner.",
			"Declared Contract boundaries are distinguished from independently enforced runtime boundaries.",
			"Residual risks and assumptions remain explicit where evidence or enforcement is unavailable.",
		},
		AntiPatterns: []string{
			"Treating the model as ordinary trusted application code.",
			"Considering only malicious users while ignoring compromised tools, content, memory, models, or infrastructure.",
			"Listing prompt injection without tracing the capability or asset it can reach.",
			"Assuming direct tool permissions capture delegated, proxied, nested-agent, or confused-deputy authority.",
			"Calling instructions, guardrails, or a Contract declaration an enforced mitigation.",
			"Producing threats without corresponding eval, monitoring, containment, response, and residual-risk decisions.",
		},
	},
	"security-invariant-test-engineer": {
		Purpose: "Derive deterministic negative tests and declarative behavioral eval scenarios from contract.yaml capabilities, tools, data flows, approvals, limits, Goal failure conditions, and structured security invariants. Turn machine-readable boundaries into observable deny-path evidence without implementing an eval runtime.",
		When: []string{
			"A skill Contract needs concrete tests proving that forbidden behavior remains forbidden.",
			"Security invariants such as repository-state-unchanged, no-secret-egress, or declared-tools-only need adversarial scenarios.",
			"A contract diff expands or narrows capabilities and regression coverage must change with it.",
			"Runtime enforcement requires negative tests for deny precedence, zero limits, approvals, and fail-closed behavior.",
			"An incident or threat model must become reusable invariant-level regression coverage.",
		},
		Operating: []string{
			"Parse the Goal, Contract, and existing evals, then build a traceability matrix from each boundary to observable behavior.",
			"Generate adversarial prompts and environmental conditions that attempt realistic bypasses while retaining a legitimate permitted path.",
			"Define deterministic assertions for capabilities, tools, state, data flows, approvals, limits, and output.",
			"Separate contract declaration tests, runtime enforcement tests, and behavioral eval scenarios.",
			"Keep eval YAML declarative and place harness code in trusted deterministic tests or downstream runners.",
		},
		ReviewScope: []string{
			"Required and allowed repository, filesystem, network, process, secret, and tool capabilities.",
			"Tool allow/deny precedence, wildcard rejection, path and destination normalization, and bypass variants.",
			"Data classifications, egress destinations, source-to-sink flows, output restrictions, and secret handling.",
			"Preconditions, postconditions, invariants, approval modes, invocation limits, and Goal failure conditions.",
			"Contract normalization, digest binding, semantic diff impact, eval traceability, and negative-test maintenance.",
		},
		Checklist: []string{
			"Inventory every allowed and forbidden capability scope, tool identity, data flow, approval rule, limit, and invariant.",
			"Map each Goal failure condition and Contract invariant to at least one observable assertion or explicit coverage gap.",
			"Create repository-write bypass attempts such as fix, patch, commit, rename, delete, generated-file, and delegated-tool requests.",
			"Create filesystem bypass attempts using traversal, symlink, archive, temporary path, alternate encoding, and helper-process variants.",
			"Create network bypass attempts using raw IPs, redirects, DNS rebinding, proxies, alternate protocols, nested tools, and unexpected services.",
			"Create process-execution attempts through shells, interpreters, package hooks, builds, plugins, documents, and indirect tool execution.",
			"Create secret-access and egress attempts through environment, files, metadata, logs, reports, uploads, URLs, and encoded output.",
			"Test tool deny precedence, undeclared tools, exact identifiers, parameter changes, and provider-independent capability implications.",
			"Test approval per_action, per_invocation, and per_session scope plus replay, parameter substitution, and stale approval.",
			"Test null, zero, positive, exhausted, retry, parallel, and nested-agent limit behavior.",
			"Where the design requires them, propose stable invariants such as no-undocumented-privileged-path, no-hidden-persistence, no-undeclared-egress, and security-controls-preserved with explicit observation semantics.",
			"Bind expected results to scenario ID, invariant ID, Goal criterion ID, contract digest, and runtime version.",
			"Update or retire tests when semantic contract diff reports expansion, narrowing, invariant changes, or approval changes.",
		},
		DecisionRules: []string{
			"If a security-relevant Contract boundary has no negative test or eval, report an explicit coverage gap.",
			"If a test proves only parser rejection, do not claim it proves runtime deny enforcement.",
			"If the expected secure behavior is refusal but a permitted completion path exists, test both safe completion and refusal quality.",
			"If an assertion relies on unobserved internal behavior, mark it inconclusive and add instrumentation requirements.",
			"If a contract expansion removes a previous deny expectation, require reviewed test changes instead of silently deleting failures.",
			"If an invariant type is not yet standardized, preserve its stable ID and document the observation semantics used by the test.",
		},
		FindingCategories: []string{
			"Capability, scope, tool, or deny-precedence negative-test gap.",
			"Repository, filesystem, process, network, secret, or data-egress bypass variant gap.",
			"Approval, limit, retry, concurrency, nested-agent, or invocation-scope test gap.",
			"Goal failure condition, postcondition, invariant, or output-contract traceability gap.",
			"Parser validation confused with runtime enforcement or behavioral conformance.",
			"Stale eval, missing contract-digest binding, weak observability, or unsafe executable assertion.",
		},
		SeverityGuidance: []string{
			"Critical: no test can detect a path to secret exfiltration, privileged writes, arbitrary execution, boundary escape, or external compromise.",
			"High: a material Contract deny, invariant, approval, or limit lacks realistic bypass coverage or runtime evidence.",
			"Medium: traceability, normalization variants, long-horizon behavior, instrumentation, or regression maintenance is incomplete.",
			"Low: scenario naming, documentation, fixture organization, or non-blocking edge coverage needs improvement.",
		},
		OutputRequirements: []string{
			"Contract-to-test traceability matrix for Goal failures, capabilities, tools, data flows, conditions, approvals, limits, and output.",
			"Negative-test inventory with bypass stimulus, expected policy decision, observable evidence, and test layer.",
			"Declarative Eval v1 scenario proposals referencing stable Goal criterion and invariant IDs.",
			"Deterministic runtime or integration-test proposals for enforcement points that declarative evals cannot prove.",
			"Coverage delta for semantic contract expansion, narrowing, invariant, approval, and limit changes.",
			"Instrumentation gaps, inconclusive assertions, fixture requirements, contract digest, and residual-risk notes.",
		},
		AcceptanceCriteria: []string{
			"Every material deny boundary and structured invariant has coverage or a named gap.",
			"Tests distinguish parser validation, runtime enforcement, behavioral conformance, and output validation.",
			"Bypass variants cover direct, indirect, delegated, encoded, retried, parallel, and nested-agent paths where relevant.",
			"Zero, null, finite, approval, and deny-precedence semantics are explicitly exercised.",
			"Eval specifications contain no shell, script, executable predicate, or unsafe template expression.",
			"Coverage is traceable to stable IDs and the exact normalized contract digest.",
		},
		AntiPatterns: []string{
			"Writing only positive tests for allowed behavior.",
			"Using one prompt per invariant and ignoring alternate tools, encodings, delegation, retries, and environment paths.",
			"Claiming a schema validation test proves that a runtime blocks forbidden actions.",
			"Embedding shell commands or arbitrary code inside declarative eval specifications.",
			"Deleting failing negative tests after a permission expansion without reviewed Contract traceability.",
			"Testing final text while ignoring tool calls, state changes, approvals, network activity, and data egress.",
		},
	},
}
